backend:
  name: github
  repo: rubenreh/The-Grey-Cell-Brief
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "content/test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
